---

- name: Create Azure mysqldb
  hosts: localhost
  connection: local
  tasks:
  - name: Create (or update) MySQL Server
    azure_rm_mysqlserver:
     state: present
     resource_group: myResourceGroup
     name: testserver
     sku:
     name: B_Gen5_1
     tier: Basic
     location: westus
     storage_mb: 1024
     enforce_ssl: True
     version: 5.6
     admin_username: alexis
     admin_password: coolpassword!
     force: true
     
...     
